version: "3.6"
services:

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
  node: 
    restart: always
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo: 
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongoDB:/data/
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypass
      - ME_CONFIG_MONGODB_URL=mongodb://admin:mypass@mongo:27017/

volumes:
  mongoDB: