version: "3.6"
services:
  nginx:
    ports:
      - "3000:80"
  node: 
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev